name: Frontend Plantastic
on:
    push:
        branches:
            - develop
            - main
    pull_request:
        branches:
            - develop
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: npm
                  cache-dependency-path: frontend/package-lock.json
            - name: Install dependencies
              run: |
                  cd frontend
                  npm ci
            - name: Run ESLint
              run: |
                  cd frontend
                  npm run eslint:github-action
            - name: Build
              run: |
                  cd frontend
                  npm run build
